numbered_command = true

use_trash = true
watch_files = true
xdg_open = true
xdg_open_fork = true


[display]
# default, hsplit
mode = "default"

automatically_count_files = false
collapse_preview = true
# ratios for parent view (optional), current view and preview
column_ratio = [1, 4, 4]
scroll_offset = 6
show_borders = true
show_hidden = false
show_icons = true
tilde_in_titlebar = true
# none, absolute, relative
line_number_style = "absolute"

# size, mtime, user, gourp, perm. can be combined with |. 
# `none` to disable, `all` to enable all
# all and none can't be combined with other options
linemode = "size"

[display.sort]
# lexical, mtime, natural, size, ext
sort_method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
max_preview_size = 2097152                           # 2MB
# preview_script = "~/.config/joshuto/preview_file.sh" # make sure it's marked as executable
preview_shown_hook_script = "~/.config/joshuto/on_preview_shown.sh"
preview_removed_hook_script = "~/.config/joshuto/on_preview_removed.sh"

[search]
# insensitive, sensitive, smart
string_case_sensitivity = "insensitive"
# see above
glob_case_sensitivity = "sensitive"
# see above
regex_case_sensitivity = "sensitive"
# see above
fzf_case_sensitivity = "insensitive"

[cmd_aliases]
q = "quit"

[tab]
# - num, dir,  all
display_mode = "all"
#
# inherit, home, root
home_page = "home"
